import { useParams, Link } from 'react-router-dom';
import { ArrowLeft, MapPin, ArrowRight, Flame, Zap, Droplets, Cog, ArrowUpRight } from 'lucide-react';
import { useSession } from '../state/SessionContext';
import { sources, sourceLabels, processFlows, interventions, reference, FIXTURE_DATE } from '../domain/fixtures';
import { exposure, intensity, scenario } from '../domain/calculations';
import { PageHeading, Stat, Tag, Notice, NotFound, compact, fmt, money, SectionHeading, ArrowLink } from '../components/Primitives';
import { HistoryChart } from '../components/Charts';
const icons = { fuel: Flame, electricity: Zap, process: Cog, waste: Droplets };
export default function FactoryDetail() {
  const { id } = useParams(), { factories, intake } = useSession(), f = factories.find(f => f.id === id);
  if (!f) return <NotFound kind="Factory" to="/factories" label="Factory index"/>;
  const records = intake.filter(i => i.factoryId === id), annualExposure = exposure(f);
  return <><Link to="/factories" className="back-link" data-testid="factory-back"><ArrowLeft size={15}/>Factory index</Link><PageHeading eyebrow={`${f.sector.toUpperCase()} / FACTORY PROFILE`} title={f.name} description={`${f.city}, ${f.state} · Illustrative facility`} action={f.coordinates ? <Link className="app-btn outline" to={`/?factory=${f.id}`} data-testid="factory-view-map"><MapPin size={16}/>View on map</Link> : <Tag id="factory-awaiting-status" tone="warning">Awaiting baseline</Tag>}/>
  {f.baseline === null ? <><Notice id="awaiting-baseline-notice">This factory is <strong>Awaiting baseline</strong>. Intake records remain separate source estimates. No coordinates, emissions total, ranking, or recommendation is assumed.</Notice><div className="awaiting-baseline"><span className="factory-sector-icon"><Flame size={30}/></span><h2 data-testid="awaiting-heading">A reliable baseline comes first.</h2><p>Annual production, complete energy and process records, and an agreed reporting boundary are still required.</p><Link to={`/intake?factory=${f.id}`} className="app-btn primary" data-testid="awaiting-add-data">Add source data<ArrowUpRight size={16}/></Link></div></> : <>
    <div className="stats-grid"><Stat id="detail-emissions" label="Annual emissions" value={compact(f.baseline)} unit="tCO₂e" note="Scope 1 + 2 · FY 2025"/><Stat id="detail-intensity" label="Emissions intensity" value={fmt(intensity(f)!, 2)} unit="tCO₂e/t" note={`${fmt(f.production!)} tonnes annual output`}/><Stat id="detail-exposure" label="Illustrative export exposure" value={annualExposure === null ? 'N/A' : money(annualExposure)} note={annualExposure === null ? 'Outside this CBAM fixture scenario' : `${f.exportShare * 100}% assumed EU export share`}/><Stat id="detail-confidence" label="Data confidence" value={f.confidence} note="Not verification readiness"/></div>
    <div className="two-columns"><section className="border-section"><SectionHeading title="Emissions hotspots" note="Annual contribution by source"/>{[...sources].sort((a, b) => f.hotspots[b] - f.hotspots[a]).map(s => { const Icon = icons[s]; return <div className="hotspot" key={s} data-testid={`hotspot-${s}`}><div className="hotspot-header"><span><Icon size={16}/>{sourceLabels[s]}</span><strong>{fmt(f.hotspots[s])} <small>tCO₂e</small></strong><span>{(f.hotspots[s] / f.baseline! * 100).toFixed(0)}%</span></div><div className="hotspot-track"><div className={`hotspot-fill source-${s}`} style={{ width: `${f.hotspots[s] / f.baseline! * 100}%` }}/></div></div>; })}</section><section className="border-section"><SectionHeading title="Emissions through the year" note="Monthly history · FY 2025 · tCO₂e"/><HistoryChart data={f.history}/></section></div>
    <section className="full-section"><SectionHeading title="Inside the process" note={`${f.sector} production flow · schematic, not an engineering diagram`}/><div className="process-flow">{processFlows[f.sector].map((s, i) => <div className="process-step" key={s} data-testid={`process-step-${i}`}><span className="process-index">0{i + 1}</span><strong>{s}</strong>{i < processFlows[f.sector].length - 1 && <ArrowRight size={18}/>}</div>)}</div></section>
    <div className="two-columns"><section className="border-section"><SectionHeading title="Operating assumptions" note="Fixture inputs used in intervention calculations"/><dl className="assumptions-list">{sources.map(s => <div key={s} data-testid={`cost-input-${s}`}><dt>{sourceLabels[s]} cost / year</dt><dd>{money(f.costs[s])}</dd></div>)}<div data-testid="waste-input"><dt>Waste generated / year</dt><dd>{fmt(f.wasteTonnes)} tonnes</dd></div><div data-testid="production-input"><dt>Annual production</dt><dd>{fmt(f.production!)} tonnes</dd></div></dl></section><section className="border-section"><SectionHeading title="Financial exposure scenario" note={`Illustrative references · ${FIXTURE_DATE}`}/><div className="exposure-value" data-testid="exposure-value">{annualExposure === null ? 'Not modelled' : money(annualExposure)}<span>gross annual exposure scenario</span></div><p className="body-small">{annualExposure === null ? 'Only steel and cement are included in this simplified demonstration scenario. This does not determine legal product scope.' : `Annual emissions × ${(f.exportShare * 100).toFixed(0)}% assumed EU exports × €${reference.carbonEUR}/tCO₂ × ₹${reference.eurINR}/€. No phase-in, free allocation, product mapping, or origin carbon-price adjustment is modelled.`}</p><Notice id="cbam-notice">Not a CBAM tax liability, compliance calculation, or legal assessment. Fixture references are not live market prices.</Notice></section></div>
    <section className="full-section"><SectionHeading title="Recommended starting points" note="Rule-based matches for the sector and documented source hotspots" action={<ArrowLink to={`/interventions?factory=${f.id}`} id="factory-all-interventions">All interventions</ArrowLink>}/><div className="recommendation-grid">{interventions.filter(i => i.sectors.includes(f.sector)).sort((a, b) => scenario(f, [b], 100).reduction - scenario(f, [a], 100).reduction).slice(0, 3).map(i => <Link className="recommendation" key={i.id} to={`/interventions/${i.id}?factory=${f.id}`} data-testid={`factory-recommendation-${i.id}`}><span className="tiny-label">{i.category}</span><h3>{i.name}<ArrowUpRight size={16}/></h3><strong>{compact(scenario(f, [i], 100).reduction)} <small>tCO₂e/yr estimated</small></strong></Link>)}</div></section>
    </>}
    <section className="full-section"><SectionHeading title="Source intake records" note="Individual source estimates; never substituted for the annual factory baseline" action={<ArrowLink to={`/intake?factory=${f.id}`} id="factory-intake-link">Add source data</ArrowLink>}/>{records.length ? <div className="intake-record-list">{records.map(r => <div key={r.id} className="intake-record" data-testid={`source-record-${r.id}`}><span>{r.sample}<small>{r.period} · {r.fileName || 'Sample fixture'}</small></span><strong>{fmt(r.emissions, 2)} tCO₂e <small>source estimate only</small></strong></div>)}</div> : <p className="muted body-small" data-testid="no-intake-records">No source records added in this session.</p>}</section>
  </>;
}