import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { UploadCloud, FileText, Zap, Flame, Recycle, Check, ArrowRight, X, LoaderCircle, ShieldCheck } from 'lucide-react';
import { useSession } from '../state/SessionContext';
import { extractionSamples } from '../domain/extraction';
import { extractEstimate } from '../domain/calculations';
import { PageHeading, Notice, Btn, Tag, fmt, money, SectionHeading } from '../components/Primitives';
const sampleIcons = [Zap, Flame, Recycle];
export default function Intake() {
  const { factories, addIntake } = useSession(), [params] = useSearchParams();
  const [factoryId, setFactoryId] = useState(params.get('factory') || factories[0].id), [sampleId, setSampleId] = useState('electricity');
  const [stage, setStage] = useState<'select' | 'processing' | 'review' | 'saved'>('select');
  const [file, setFile] = useState<{ name: string; size: number } | null>(null), [error, setError] = useState('');
  const [quantity, setQuantity] = useState(''), [factor, setFactor] = useState(''), [rate, setRate] = useState(''), [period, setPeriod] = useState('2025-12');
  const [cancelled, setCancelled] = useState(false), [dragOver, setDragOver] = useState(false);
  const timer = useRef<number | null>(null), saved = useRef(false), fileInput = useRef<HTMLInputElement>(null);
  const sample = extractionSamples.find(s => s.id === sampleId)!, factory = factories.find(f => f.id === factoryId);
  const invalid = !quantity.trim() || !factor.trim() || !rate.trim() || [Number(quantity), Number(factor), Number(rate)].some(n => !Number.isFinite(n) || n < 0) || !/^\d{4}-\d{2}$/.test(period);
  let estimate = { emissions: 0, cost: 0 }; let calculationError = invalid;
  if (!invalid) { try { estimate = extractEstimate(Number(quantity), Number(factor), Number(rate)); } catch { calculationError = true; } }
  useEffect(() => () => { if (timer.current) clearTimeout(timer.current); }, []);
  const capture = (f?: File) => { if (!f) return; setError(''); if (f.size > 20 * 1024 * 1024) { setError('Choose a file smaller than 20 MB. Only its name and size will be captured.'); return; } setFile({ name: f.name, size: f.size }); setCancelled(false); };
  const start = () => { if (!factory) return; saved.current = false; setCancelled(false); setStage('processing'); timer.current = window.setTimeout(() => { setQuantity(String(sample.quantity)); setFactor(String(sample.factor)); setRate(String(sample.rate)); setPeriod(sample.period); setStage('review'); }, 1500); };
  const cancel = () => { if (timer.current) clearTimeout(timer.current); setStage('select'); setCancelled(true); };
  const confirm = () => { if (calculationError || !factory || saved.current) return; saved.current = true; addIntake({ factoryId, sample: sample.name, fileName: file?.name || null, fileSize: file?.size ?? null, quantity: Number(quantity), factor: Number(factor), unit: sample.unit, costRate: Number(rate), emissions: estimate.emissions, cost: estimate.cost, period }); setStage('saved'); };
  return <><PageHeading eyebrow="BETTER INPUTS. CLEARER DECISIONS." title="Data Intake" description="Bring a source record into focus, review the assumptions, and capture an estimate." action={<Tag id="intake-simulation-tag" tone="blue">Simulated extraction</Tag>}/>
    <div className="stepper" aria-label="Intake progress" data-testid="intake-progress">{['Choose a source', 'Review extraction', 'Confirm estimate'].map((s, i) => <div key={s} className={(stage === 'saved' ? 2 : stage === 'review' ? 1 : 0) >= i ? 'current' : ''}><span>{stage === 'saved' || (stage === 'review' && i === 0) ? <Check size={15}/> : `0${i + 1}`}</span><strong>{s}</strong>{i < 2 && <div className="step-line"/>}</div>)}</div>
    <Notice id="intake-disclosure">Demonstration only. File names and sizes are captured; document contents are <strong>never read or uploaded</strong>. All extraction results come from editable sample fixtures, not OCR or AI.</Notice>
    {!factory && <div className="notice warning" role="alert" data-testid="intake-invalid-factory">The requested factory is unavailable. Select a factory below to continue.</div>}
    {stage === 'saved' ? <div className="intake-success" data-testid="intake-success"><span className="success-icon"><Check size={30}/></span><div className="eyebrow">SOURCE RECORD CONFIRMED</div><h2 data-testid="intake-success-heading">One source. A more informed estimate.</h2><p><strong>{fmt(estimate.emissions, 2)} tCO₂e</strong> recorded for {factory?.name} · {period}.</p><Notice id="intake-baseline-unchanged">This record covers <strong>one source for {period}</strong>. It does not change the annual baseline on its own{factory?.baseline === null ? ', which is still Awaiting baseline' : `, which stays at ${fmt(factory?.baseline || 0)} tCO₂e`}. Apply it on the process page to set or revise the baseline.</Notice><div className="button-row"><Btn data-testid="intake-another" onClick={() => { setStage('select'); setFile(null); saved.current = false; }}>Add another source</Btn><Link className="app-btn primary" to={`/factories/${factoryId}/profile`} data-testid="intake-apply-baseline">{factory?.baseline === null ? 'Set the baseline' : 'Revise the baseline'}<ArrowRight size={16}/></Link><Link className="app-btn outline" to={`/factories/${factoryId}`} data-testid="intake-view-factory">View factory<ArrowRight size={16}/></Link></div></div> : <div className="intake-layout"><section><SectionHeading title={stage === 'review' ? 'Review the sample extraction' : 'Choose your source'} note={stage === 'review' ? 'All values are editable before confirmation' : 'A record belongs to one factory and one reporting period'}/><label className="field-label">Factory<select data-testid="intake-factory" value={factoryId} disabled={stage !== 'select'} onChange={e => setFactoryId(e.target.value)}>{!factory && <option value={factoryId}>Select a valid factory</option>}{factories.map(f => <option key={f.id} value={f.id}>{f.name}{f.baseline === null ? ' — Awaiting baseline' : ''}</option>)}</select></label>
      {stage === 'select' && <><div className={`upload-zone ${dragOver ? 'dragover' : ''}`} onDragOver={e => { e.preventDefault(); setDragOver(true); }} onDragLeave={() => setDragOver(false)} onDrop={e => { e.preventDefault(); setDragOver(false); capture(e.dataTransfer.files[0]); }} data-testid="file-drop-zone"><UploadCloud size={33} strokeWidth={1.4}/><strong>{file ? file.name : 'Drop a source document here'}</strong><p>{file ? `${fmt(file.size)} bytes · Metadata captured only` : 'PDF, image, or spreadsheet · up to 20 MB'}</p><input ref={fileInput} className="sr-only" type="file" aria-label="Choose source document metadata" accept=".pdf,.png,.jpg,.jpeg,.webp,.csv,.xlsx,.xls,.txt,.docx" data-testid="intake-file" onChange={e => capture(e.target.files?.[0])}/><div className="button-row"><Btn data-testid="browse-file" onClick={() => fileInput.current?.click()}>{file ? 'Change file' : 'Browse files'}</Btn>{file && <Btn data-testid="remove-file" aria-label="Remove selected file" className="icon-btn" onClick={() => { setFile(null); if (fileInput.current) fileInput.current.value = ''; }}><X size={15}/></Btn>}</div><small>Optional · sample flows also work without a file</small></div>{error && <p role="alert" className="field-error" data-testid="intake-file-error">{error}</p>}
      <div className="sample-divider"><span>SELECT A SAMPLE FLOW</span></div><div className="sample-grid">{extractionSamples.map((s, i) => { const Icon = sampleIcons[i]; return <button className={`sample-card ${sampleId === s.id ? 'selected' : ''}`} key={s.id} data-testid={`sample-${s.id}`} aria-pressed={sampleId === s.id} onClick={() => setSampleId(s.id)}><Icon size={23} strokeWidth={1.5}/><strong>{s.name}</strong><span>{s.kind}</span>{sampleId === s.id && <Check size={15} className="sample-check"/>}</button>; })}</div>{cancelled && <p role="status" className="cancelled-message" data-testid="extraction-cancelled">Extraction cancelled. No source record was saved.</p>}<div className="form-bottom"><span className="muted"><ShieldCheck size={14}/>No document content leaves your browser</span><Btn variant="primary" data-testid="run-extraction" disabled={!factory} onClick={start}>Run sample extraction<ArrowRight size={16}/></Btn></div></>}
      {stage === 'processing' && <div className="processing-state" role="status" data-testid="extraction-processing"><LoaderCircle size={35} className="spin"/><h2>Preparing sample fields…</h2><p>Simulated flow · no document is being read</p><Btn data-testid="cancel-extraction" onClick={cancel}>Cancel extraction</Btn></div>}
      {stage === 'review' && <><div className="extraction-source" data-testid="extraction-source"><FileText size={22}/><div><strong>{file?.name || sample.filename}</strong><span>{sample.name} · Fixture-derived fields</span></div><Tag id="extraction-confidence" tone={sample.confidence === 'High' ? 'success' : 'warning'}>{sample.confidence} confidence</Tag></div><div className="form-grid extraction-fields"><label>Quantity ({sample.unit})<input type="number" min="0" step="any" data-testid="extraction-quantity" value={quantity} onChange={e => setQuantity(e.target.value)}/><small>Fixture confidence: {sample.confidence}</small></label><label>Emission factor (tCO₂e / {sample.unit})<input type="number" min="0" step="any" data-testid="extraction-factor" value={factor} onChange={e => setFactor(e.target.value)}/><small>Assumed reference · editable</small></label><label>Unit cost (₹ / {sample.unit})<input type="number" min="0" step="any" data-testid="extraction-rate" value={rate} onChange={e => setRate(e.target.value)}/><small>Illustrative cost, excluding tax</small></label><label>Reporting month<input type="month" data-testid="extraction-period" value={period} onChange={e => setPeriod(e.target.value)}/><small>Single-period record</small></label></div>{calculationError && <p role="alert" className="field-error" data-testid="extraction-validation-error">Enter non-negative finite numbers and a reporting month.</p>}<Notice id="extraction-factor-assumptions">{sample.note} Edits recalculate the source estimate immediately. Confidence is descriptive, not verification.</Notice><div className="form-bottom"><Btn data-testid="discard-extraction" onClick={cancel}>Discard extraction</Btn><Btn variant="primary" data-testid="confirm-extraction" disabled={calculationError || !factory} onClick={confirm}>Confirm source estimate<Check size={16}/></Btn></div></>}
    </section><aside className="intake-summary"><span className="eyebrow">ESTIMATE PREVIEW</span><h2 data-testid="intake-summary-title">{sample.name}</h2><Tag id="intake-estimate-status" tone={stage === 'review' ? 'blue' : 'neutral'}>{stage === 'review' ? 'Ready for review' : 'Awaiting extraction'}</Tag><div className="estimate-metric"><span>Source emissions</span><strong data-testid="intake-estimate-emissions">{stage === 'review' && !calculationError ? fmt(estimate.emissions, 2) : '—'}<small>tCO₂e</small></strong></div><div className="estimate-metric"><span>Source operating cost</span><strong data-testid="intake-estimate-cost">{stage === 'review' && !calculationError ? money(estimate.cost) : '—'}</strong></div><div className="estimate-formula" data-testid="intake-formula"><span>CALCULATION</span><p>Activity quantity × emission factor</p><p>Activity quantity × unit cost</p></div></aside></div>}
  </>;
}